cajachica/urls.py
from django.contrib import admin
from django.urls import path
from myapp.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('reiniciar-secuencia/', reiniciar_secuencia, name='reiniciar_secuencia'),
    path('',login_view, name='login'),
    path('dashboard/',dashboard_view, name='dashboard'),
    path('ingreso/', ingreso, name='ingreso'),
    path('gasto/', gasto, name='gasto'),
    path('rendicion/', rendicion, name='rendicion'),
    path('logout/',logout_view, name='logout'),
    path('cajachica/', caja_chica, name='caja_chica'),
    path('rendiciones/<int:gasto_id>/', registrar_rendiciones, name='registrar_rendiciones'),
    path('guardar_oficial/', guardar_oficial, name='guardar_oficial'),
    path('edit_item/<int:id>/<str:tipo>/', edit_item, name='edit_item'),
    path('edit_item/<int:id>/Gasto/', gasto_edit, name='gasto_edit'),
    path('registrar_gasto/<int:id>/', registrar_gasto, name='registrar_gasto'),
    path('editar_ingreso/<int:id>/', editar_ingreso, name='editar_ingreso'),
    path('proveedores/',proveedores, name='proveedores'),
    path('guardar-proveedor/', guardar_proveedor, name='guardar_proveedor'),
    path('proveedores/editar/', editar_proveedor, name='editar_proveedor'),
    path('api/proveedores/', buscar_proveedores, name='buscar_proveedores'),
    path('prueba/', prueba, name='prueba'),
    path('proveedores/eliminar/<int:proveedor_id>/', eliminar_proveedor, name='eliminar_proveedor'),
    path('get_nivel_2_conceptos/', get_nivel_2_conceptos, name='get_nivel_2_conceptos'),
    path('get_nivel_3_conceptos/', get_nivel_3_conceptos, name='get_nivel_3_conceptos'),
    path('reportes/', reportes, name='reportes'),
    path('generar_reporte_json/',generar_reporte_json, name='generar_reporte_json'),
    path('conceptos/', conceptos, name='conceptos'),
    path('crear_concepto/', crear_concepto, name='crear_concepto'),
    path('editar_concepto/<int:id>/', editar_concepto, name='editar_concepto'),
    path('eliminar_concepto/<int:id>/', eliminar_concepto, name='eliminar_concepto'),
    path('guardar_cuenta_bancaria/', guardar_cuenta_bancaria, name='guardar_cuenta_bancaria'),
    path('proveedores/<int:proveedor_id>/cuentas/', cuentas_bancarias, name='cuentas_bancarias'),
    path('actualizar-movimiento/', actualizar_movimiento, name='actualizar_movimiento'),
    path('ficha-ingreso/', ficha_ingreso_view, name='ficha_ingreso'),
    path('agregar_banco/', agregar_banco, name='agregar_banco'),
    path('descargarexcel/', descargar_excel, name='descargarexcel'),
    path('prestamos/', prestamos, name='prestamos'),
    path('ver_prestamos/', ver_prestamos, name='ver_prestamos'),
    path('realizar_pago/', realizar_pago, name='realizar_pago'),
    path('reporte-anual/', reporte_anual, name='reporte_anual'),
    path('guardar_datos/', guardar_datos1, name='guardar_datos'),
    path('ver_personal/', ver_personal, name='ver_personal'),
    path('editar_personal/<int:id>/', editar_personal, name='editar_personal'),
    path('crear_contraseña/<int:personal_id>/', crear_contraseña, name='crear_contraseña'),
    path('generar_pdf/<int:persona_id>/', generar_pdf, name='generar_pdf'),
    path('editar-ficha/<int:id_personal>/', guardar_datos_editados, name="guardar_datos_editados"),
    path('reporte-mensual/', reporte_mensual, name='reporte_mensual'),
    path('reporte-diario/', generar_reporte_diario, name='reporte_diario'),
    path('cerrar-caja/', cerrar_caja, name='cerrar_caja'),
    path("cerrar-caja-usuario/<int:user_id>/", cerrar_caja_usuario, name="cerrar_caja_usuario"),
    path("reactivar-caja-usuario/<int:user_id>/", reactivar_caja_usuario, name="reactivar_caja_usuario"),
    path("registrar-usuario/", registrar_usuario, name="registrar_usuario"),
    path('transferir-yape/', transferir_yape, name='transferir_yape'),
    path('proveedores/verificar_gastos/<int:proveedor_id>/', verificar_gastos, name='verificar_gastos'),
    path('reporte_proveedor_pdf/', reporte_proveedor_pdf, name='reporte_proveedor_pdf'),
    path('reporte_proveedor_excel/', reporte_proveedor_excel, name='reporte_proveedor_excel'),
    path('trigger-error/', trigger_error, name='trigger_error'),
    path('eliminar-item/<int:item_id>/<str:item_tipo>/', eliminar_item, name='eliminar_item'),
    path('reporte-concepto-proveedor-pdf/', reporte_concepto_proveedor_pdf, name='reporte_concepto_proveedor_pdf'),
    path('generar-pdf-personal/', generar_pdf_personal, name='generar_pdf_personal'),
    path('ver-rendidos/', ver_rendidos, name='ver_rendidos'),
    path('gasto/<int:gasto_id>/rendiciones/', ver_rendiciones_asociadas, name='ver_rendiciones_asociadas'),
    path('crear_pdf_rendicion/<int:gasto_id>/', crear_pdf_rendicion, name='crear_pdf_rendicion'),
    path("generar-pdf-rendiciones/", generar_pdf_rendiciones, name="generar_pdf_rendiciones"),
    path('ver_pagos/<int:prestamo_id>/', ver_pagos, name='ver_pagos'),
    path('finalizar_cuota/<int:prestamo_id>/', finalizar_cuota, name='finalizar_cuota'),
    path('reporte-diario-conceptos/', reporte_diario_conceptos, name='reporte_diario_conceptos'),

        #Calendario
    path('calendario/', ver_calendar, name='ver_calendar'),
    path('crear-evento/', crear_evento, name='crear_evento'),
    path('obtener-eventos/', obtener_eventos, name='obtener_eventos'),
    path('eliminar-evento/', eliminar_evento, name='eliminar_evento'),
    path('eliminar-ocurrencia-evento/', eliminar_ocurrencia_evento, name='eliminar_ocurrencia_evento'),
    path('pagar-evento/', pagar_evento, name='pagar_evento'),
    path('obtener-eventos-pagados/', obtener_eventos_pagados, name='obtener_eventos_pagados'),
    path('actualizar_evento/', actualizar_evento, name='actualizar_evento'),
    path('gasto_calendario/', gasto_calendario, name='gasto_calendario'),
    path('obtener-total-mes/', obtener_total_mes, name='obtener_total_mes'),
    path('generar_reporte_pdf_calendario/', generar_reporte_pdf_calendario, name='generar_reporte_pdf_calendario'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Agrega los handlers de error aquí:
handler404 = 'myapp.views.custom_404'
handler500 = 'myapp.views.custom_500'

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings



class Evento(models.Model):
    titulo = models.CharField(max_length=200)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField(null=True, blank=True)
    recurrencia = models.CharField(
        max_length=20,
        choices=(
            ('none', 'No se repite'),
            ('daily', 'Diario'),
            ('weekly', 'Semanal'),
            ('monthly', 'Mensual'),
        ),
        default='none'
    )

    monto = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    notas = models.TextField(blank=True)
    creado_por = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    prestamo = models.BooleanField(default=False, verbose_name="Prestamo")  # Nuevo campo
    evento_pagado = models.BooleanField(default=False, verbose_name="Evento Pagado")  # Nuevo campo

    def __str__(self):
        return self.titulo

class OcurrenciaEvento(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, related_name='ocurrencias')
    fecha = models.DateField()
    pagado = models.BooleanField(default=False)
    # Puedes agregar otros campos, como observaciones específicas de la ocurrencia
    def __str__(self):
        return f"{self.evento.titulo} - {self.fecha}"





class SaldoInicial(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name="saldo_inicial")
    monto_saldo_inicial = models.DecimalField(max_digits=15, decimal_places=2, help_text="Saldo inicial del usuario")
    monto_saldo_inicial_yape = models.DecimalField(max_digits=15, decimal_places=2, help_text="Saldo inicial del usuario yape")
    caja_cerrada = models.BooleanField(default=False, help_text="Indica si la caja del usuario está cerrada")
    fecha_cierre = models.DateField(null=True, blank=True, help_text="Fecha en la que se cerró la caja")

    def __str__(self):
        return f"{self.usuario.username} - Saldo Inicial: {self.monto_saldo_inicial}"

class Fondo(models.Model):
    nombre_fondo = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre_fondo


class Banco(models.Model):
    nombre = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.nombre

class Proveedor(models.Model):
    ruc_dni = models.CharField(max_length=13, unique=True)
    razon_social = models.CharField(max_length=255)
    nombre_comercial = models.CharField(max_length=255, null=True, blank=True)
    telefono = models.CharField(max_length=15, null=True, blank=True)
    nombre_contacto = models.CharField(max_length=255, null=True, blank=True)  # Nombre del contacto principal

    def __str__(self):
        return self.nombre_comercial or self.razon_social

class CuentaBancaria(models.Model):
    proveedor = models.ForeignKey(
        Proveedor,
        on_delete=models.CASCADE,  # Si se elimina un proveedor, se eliminan sus cuentas bancarias
        related_name="cuentas_bancarias"
    )
    nombre_banco = models.CharField(max_length=255)  # Nombre del banco
    numero_cuenta = models.CharField(max_length=50)  # Número de cuenta bancaria
    tipo_cuenta = models.CharField(
        max_length=50,
        choices=[
            ('ahorros', 'Cuenta de Ahorros'),
            ('corriente', 'Cuenta Corriente'),
            ('otro', 'Otro')
        ],
        default='ahorros'
    )
    cci = models.CharField(max_length=50, blank=True, null=True)  # Código de Cuenta Interbancaria (CCI)

    def __str__(self):
        return f"{self.nombre_banco} - {self.numero_cuenta}"

# Modelo para la tabla "Local"
class Local(models.Model):
    nombre_local = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre_local


# Modelo para la tabla "Concepto"
class Concepto(models.Model):
    concepto_nombre = models.CharField(max_length=255)
    nivel = models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3')])
    id_concepto_padre = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='subconceptos')

    def __str__(self):
        return self.concepto_nombre

class Pago(models.Model):
    prestamo = models.ForeignKey('Prestamo', on_delete=models.CASCADE, related_name="pagos")
    cuota = models.PositiveIntegerField()  # Número de la cuota (ej. 1, 2, 3...)
    monto_pagado = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_pago = models.DateField()
    notas = models.TextField(blank=True, null=True)  # Nuevo campo agregado

    def __str__(self):
        return f"Pago {self.id} - Cuota {self.cuota} - Monto: {self.monto_pagado}"


# Modelo para la tabla "CajaChica"
class CajaChica(models.Model):
    fecha = models.DateField()
    saldo_inicial = models.DecimalField(max_digits=10, decimal_places=2)
    ingresos_totales = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    gastos_totales = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    saldo_final = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    cerrado = models.BooleanField(default=False)

    def calcular_saldo_final(self):
        self.saldo_final = self.saldo_inicial + self.ingresos_totales - self.gastos_totales

    def save(self, *args, **kwargs):
        self.calcular_saldo_final()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Caja Chica {self.id} - Fecha: {self.fecha}"

from datetime import date

class Gasto(models.Model):
    usuario_creador = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='gastos_creados')
    fecha_registro = models.DateField(auto_now_add=True,blank=True, null=True)  # Esta l¨ªnea agregar¨¢ la fecha autom¨¢tica
    fecha_gasto = models.DateField(blank=True, null=True)
    concepto_nivel_1 = models.ForeignKey(Concepto, null=True, blank=True, related_name='nivel_1', on_delete=models.CASCADE)
    concepto_nivel_2 = models.ForeignKey(Concepto, null=True, blank=True, related_name='nivel_2', on_delete=models.CASCADE)
    concepto_nivel_3 = models.ForeignKey(Concepto, null=True, blank=True, related_name='nivel_3', on_delete=models.CASCADE)
    nombre_proveedor = models.ForeignKey(Proveedor,on_delete=models.SET_NULL,null=True,blank=True,related_name='gastos')
    local = models.ForeignKey(Local, null=True, blank=True, on_delete=models.SET_NULL, related_name='gastos_local')
    tipo_comprobante = models.CharField(max_length=50, null=True, blank=True)
    num_comprobante = models.CharField(max_length=80, null=True, blank=True)  # Campo agregado
    fecha_emision_comprobante = models.DateField(null=True, blank=True)  # Campo agregado
    numero_comprobante = models.CharField(max_length=80, null=True, blank=True)
    tipo_pago = models.CharField(max_length=50, null=True, blank=True)
    fecha_operacion = models.DateField(null=True, blank=True)
    codigo_operacion = models.CharField(max_length=50, null=True, blank=True)
    observacion = models.TextField(null=True, blank=True)
    importe = models.DecimalField(max_digits=10, decimal_places=2)
    moneda = models.CharField(max_length=50)
    rendido = models.BooleanField(default=False, null=True, blank=True)  # Nuevo campo agregado
    fecha_rendido = models.DateField(null=True, blank=True)

    # Nuevos campos
    id_requerimiento = models.CharField(max_length=100, null=True, blank=True)  # Campo nuevo para identificar el requerimiento
    num_requerimiento = models.CharField(max_length=100, null=True, blank=True)  # Campo nuevo para identificar el requerimiento
    campo_area = models.CharField(
        max_length=50,
        choices=[
            ('Sistemas', 'Sistemas'),
            ('Academico', 'Academico'),
            ('Imagen', 'Imagen'),
            ('Gerencia', 'Gerencia'),
            ('Administracion', 'Administracion'),
            ('Marketing', 'Marketing'),
            ('Ventas', 'Ventas'),
        ],
        null=True,
        blank=True
    )
    campo_mes = models.CharField(
        max_length=20,
        choices=[
            ('Enero', 'Enero'),
            ('Febrero', 'Febrero'),
            ('Marzo', 'Marzo'),
            ('Abril', 'Abril'),
            ('Mayo', 'Mayo'),
            ('Junio', 'Junio'),
            ('Julio', 'Julio'),
            ('Agosto', 'Agosto'),
            ('Septiembre', 'Septiembre'),
            ('Octubre', 'Octubre'),
            ('Noviembre', 'Noviembre'),
            ('Diciembre', 'Diciembre'),
        ],
        null=True,
        blank=True
    )
    banco = models.ForeignKey(Banco,on_delete=models.SET_NULL,null=True,blank=True,related_name='gastos_banco')
    # Relación con el préstamo
    prestamo = models.ForeignKey('Prestamo', null=True, blank=True, on_delete=models.SET_NULL, related_name='gastos')
    gasto_origen = models.ForeignKey(
        'self',  # Relación consigo mismo
        null=True,
        blank=True,
        on_delete=models.CASCADE,  # Si se borra el gasto original, se borran los generados
        related_name='gastos_generados'
    )

    def concepto_mayor_nivel(self):
        """
        Retorna el concepto de mayor nivel disponible (3, 2 o 1).
        """
        return self.concepto_nivel_3 or self.concepto_nivel_2 or self.concepto_nivel_1
    def __str__(self):
        return f"Gasto {self.id} - Proveedor: {self.nombre_proveedor or 'Sin proveedor'}"



class Rendicion(models.Model):
    usuario_creador = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='rendiciones_creadas'
    )
    fecha_registro = models.DateField(auto_now_add=True,blank=True, null=True)  # Esta linea agregar la fecha autom¨¢tica
    fecha_operacion = models.DateField(blank=True, null=True)  # Fecha de la operacion
    descripcion = models.TextField(blank=True, null=True)  # Descripcion

templates/ingreso.html
{% extends 'base.html' %}

{% block content %}
<style>
  /* Fondo oscuro con bordes redondeados y sombra */
.dynamic-section {
  background-color: #343a40; /* Fondo oscuro */
  color: #fff; /* Texto blanco */
  padding: 15px; /* Espaciado interno */
  border-radius: 8px; /* Bordes redondeados */
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Sombra ligera */
  margin-bottom: 20px; /* Espaciado inferior */
}

/* Estilo de las etiquetas */
.dynamic-label {
  display: block; /* Ocupa toda la fila */
  font-size: 14px; /* Tamaño del texto */
  font-weight: 500; /* Peso intermedio */
  margin-bottom: 5px; /* Espaciado inferior */
}

/* Estilo de los inputs */
.dynamic-input {
  width: 100%; /* Ancho completo */
  padding: 10px; /* Espaciado interno */
  border: 1px solid #ced4da; /* Borde gris claro */
  border-radius: 5px; /* Bordes redondeados */
  font-size: 14px; /* Tamaño del texto */
  background-color: #495057; /* Fondo oscuro del input */
  color: #fff; /* Texto blanco */
}

/* Placeholder en color gris claro */
.dynamic-input::placeholder {
  color: #adb5bd; /* Gris claro */
}

/* Input en estado de enfoque */
.dynamic-input:focus {
  outline: none; /* Eliminar borde por defecto */
  border-color: #17a2b8; /* Color del borde al enfocar */
  box-shadow: 0 0 4px rgba(23, 162, 184, 0.5); /* Sombra al enfocar */
}

/* Cambiar el estilo del input type="date" para que coincida */
input[type="date"].dynamic-input {
  color-scheme: dark; /* Cambia el esquema de colores al oscuro para compatibilidad */
}
</style>
<!-- Incluir Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

<main class="flex-1 p-8">
  <h2 class="text-3xl font-bold mb-6">Registrar Ingresos en Caja</h2>
<!-- Botón de Agregar Banco -->
<div class="mb-6">
  <button type="button" class="bg-green-600 hover:bg-green-700 text-white p-3 rounded-lg transition duration-300" onclick="openModal('agregarBancoModal')">
    Agregar Banco
  </button>
</div>
  <!-- Formulario -->
  <div class="bg-white shadow-md rounded-lg p-6">
    <form method="POST" action="{% url 'ingreso' %}" id="formulario-ingreso" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {% csrf_token %}
      <!-- Fecha -->
      <div>
        <label for="fecha" class="block text-sm font-medium text-gray-700">Fecha:</label>
        <input type="date" id="fecha" name="fecha" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-accent focus:border-accent" required>
      </div>

      <!-- Importe -->
      <div>
        <label for="importe" class="block text-sm font-medium text-gray-700">Importe:</label>
        <input type="number" id="importe" name="importe" step="0.01" placeholder="0.00" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-accent focus:border-accent" required>
      </div>

      <!-- Fondo -->
      <div>
        <label for="id_fondo" class="block text-sm font-medium text-gray-700">Fondo:</label>
        <select id="id_fondo" name="id_fondo" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-accent focus:border-accent" required>
            {% for fondo in fondos %}
                <option value="{{ fondo.id }}">
                    {{ fondo.nombre_fondo }}
                </option>
            {% endfor %}
        </select>

      </div>

      <!-- Método de Pago -->
      <div>
        <label for="metodo_pago" class="block text-sm font-medium text-gray-700">Método de Pago:</label>
        <select id="metodo_pago" name="metodo_pago" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-accent focus:border-accent">
            <option value="efectivo">Efectivo</option>
          <option value="yape">Yape</option>
            <option value="Deposito en cuenta">Deposito en Cuenta</option>
          <option value="IZIPAY">IZIPAY</option>
          <option value="IZIPAY YA">IZIPAY YA</option>
          <option value="transferencia">Transferencia</option>

        </select>
      </div>

      <!-- Moneda -->
      <div>
        <label for="moneda" class="block text-sm font-medium text-gray-700">Moneda:</label>
        <select id="moneda" name="moneda" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-accent focus:border-accent">
          <option value="Soles">Soles</option>
        </select>
      </div>

      <!-- Local -->
      <div>
        <label for="local" class="block text-sm font-medium text-gray-700">Local:</label>
        <select id="local" name="local" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-accent focus:border-accent">
          {% for loc in locales %}
          <option value="{{ loc.id }}">{{ loc.nombre_local }}</option>
          {% endfor %}
        </select>
      </div>

    <!-- Banco (dinámico) -->
    <div id="banco-container" class="dynamic-section" style="display: none;">
      <label for="banco_operacion" class="dynamic-label">Banco :</label>

      <!-- Select de Banco -->
      <select id="banco_operacion" name="banco_operacion" class="dynamic-input">
        <option value="" disabled selected>Seleccionar Banco</option>
        {% for banco in bancos %}
          <option value="{{ banco.id }}">{{ banco.nombre }}</option>
        {% endfor %}
      </select>

    </div>



    <!-- Código de Operacion (dinámico) -->
    <div id="codigo-operacion-container" class="dynamic-section" style="display: none;">
      <label for="codigo_operacion" class="dynamic-label">Código de Operación:</label>
      <input type="text" id="codigo_operacion" name="codigo_operacion" class="dynamic-input" placeholder="Código de operación">
    </div>

    <!-- Fecha de Operacion (dinámico) -->
    <div id="fecha-operacion-container" class="dynamic-section" style="display: none;">
      <label for="fecha_operacion" class="dynamic-label">Fecha de Operación:</label>
      <input type="date" id="fecha_operacion" name="fecha_operacion" class="dynamic-input">
    </div>

      <!-- Observacion -->
      <div class="col-span-1 md:col-span-2 lg:col-span-3">
        <label for="observacion" class="block text-sm font-medium text-gray-700">Observación:</label>
        <textarea id="observacion" name="observacion" rows="3" placeholder="Escribe aquí..." class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-accent focus:border-accent"></textarea>
      </div>

      <!-- Botón de Guardar -->
      <div class="col-span-1 md:col-span-2 lg:col-span-3 text-right">
        <button type="button" id="btn-guardar" class="bg-accent text-white px-4 py-2 rounded shadow hover:bg-green-600">
          Guardar
        </button>
      </div>
    </form>
  </div>
</main>
<!-- Modal para agregar banco -->
<div id="agregarBancoModal" class="fixed inset-0 z-50 hidden bg-gray-800 bg-opacity-50 overflow-y-auto">
    <div class="flex items-center justify-center min-h-screen">
        <!-- Contenido del Modal -->
        <div class="bg-white rounded-lg shadow-lg p-6 w-full max-w-lg">
            <h2 class="text-2xl font-bold mb-4 text-center">Agregar Banco</h2>
            <!-- Formulario de agregar banco -->
            <form method="POST" action="{% url 'agregar_banco' %}">
                {% csrf_token %}
                <div class="mb-4">
                    <label for="id_nombre" class="block text-sm font-medium text-gray-700">Nombre del Banco</label>
                    <input type="text" id="id_nombre" name="nombre" class="w-full mt-1 px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" placeholder="Nombre del Banco" required>
                </div>

                <div class="flex justify-end space-x-4">
                    <button type="button" class="bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-600" onclick="closeModal('agregarBancoModal')">Cerrar</button>
                    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
  // Función para abrir el modal
  function openModal(modalId) {
      document.getElementById(modalId).classList.remove('hidden');
  }

  // Función para cerrar el modal
  function closeModal(modalId) {
      document.getElementById(modalId).classList.add('hidden');
  }
</script>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const metodoPagoSelect = document.getElementById('metodo_pago');
    const codigoOperacionContainer = document.getElementById('codigo-operacion-container');
    const fechaOperacionContainer = document.getElementById('fecha-operacion-container');
    const bancoContainer = document.getElementById('banco-container');


    const btnGuardar = document.getElementById('btn-guardar');
    const formulario = document.getElementById('formulario-ingreso');
    const selectFondo = document.getElementById("id_fondo");
    const esStaff = "{{ request.user.is_staff|lower }}" === "true"; // Verifica si el usuario es staff

    if (!esStaff) {
      for (let option of selectFondo.options) {
        if (option.text.trim() === "Sin especificar") {
          option.selected = true;
          break;
        }
      }
      selectFondo.setAttribute("readonly", true);
      selectFondo.style.pointerEvents = "none"; // Evita interacción visualmente
    }
    // Mostrar/Ocultar campo Código de Operacion
    metodoPagoSelect.addEventListener('change', () => {
      if (metodoPagoSelect.value !== 'efectivo') {
        codigoOperacionContainer.style.display = 'block';
        fechaOperacionContainer.style.display = 'block';
         bancoContainer.style.display='block';
      } else {
        codigoOperacionContainer.style.display = 'none';
        fechaOperacionContainer.style.display = 'none';
        bancoContainer.style.display='none';
      }
    });

    // Confirmacion antes de enviar el formulario
    btnGuardar.addEventListener('click', (e) => {
      e.preventDefault();
      Swal.fire({
        title: "¿Estás seguro?",
        text: "Estás a punto de registrar un ingreso en la caja chica.",
        icon: "warning",
        showCancelButton: true,
        confirmButtonText: "Sí, guardar",
        cancelButtonText: "Cancelar",
        reverseButtons: true
      }).then((result) => {
        if (result.isConfirmed) {
          formulario.submit();
        }
      });
    });
  });
</script>

<!-- Incluyendo mensajes -->
{% include 'mensaje.html' %}
{% endblock %}